attractor/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('traveler.urls')),
    path("api/", include('traveler.api.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

traveler/api/urls.py
from django.urls import path
from rest_framework_jwt.views import obtain_jwt_token
from . import views

app_name = 'api'

urlpatterns = [
    path('country/', views.CountryListAPIView.as_view(), name="country-list"),
    path('country/<int:pk>/', views.CountryRUDAPIView.as_view(), name="country-rud"),
    path("post/", views.PostListAPIView.as_view(), name="post-list"),
    path("post/<int:pk>/", views.PostRUDAPIView.as_view(), name="post-rud"),
    path("comment/", views.PostCommentListAPIView.as_view(), name="comment-list"),
    path("comment/<int:pk>/", views.PostCommentRUDAPIView.as_view(), name="comment-rud"),
    path("picture/", views.PostImageListAPIView.as_view(), name="postimage-list"),
    path("picture/<int:pk>/", views.PostImageRUDAPIView.as_view(), name="postimage-rud"),

    # authorization
    path('account/', views.AccountListAPIView.as_view(), name="account-list"),
    path('account/signup/', views.UserSignupAPIView.as_view(), name="signup"),
    path('account/token/', obtain_jwt_token, name="token"),
    path('account/<int:pk>/', views.AccountRUDAPIView.as_view(), name="account-rud")
]

traveler/urls.py
from django.urls import path
from . import views

app_name = 'traveler'

urlpatterns = [
    path('', views.HomeView.as_view(), name="home"),
    path('dash/', views.DashView.as_view(), name="dash"),
    path('post/create/', views.PostCreateView.as_view(), name="post-create"),
    path('post/<int:pk>/', views.PostDetailView.as_view(), name="post-detail"), # needs to be removed
    path('country/', views.CountryListView.as_view(), name="country-list"),
    path('country/<int:pk>/', views.CountryDetailView.as_view(), name="country-detail"),
    path('login/', views.LoginView.as_view(), name="login"),
    path('signup/', views.SignupView.as_view(), name="signup"),
    path('logout/', views.LogoutView.as_view(), name="logout"),
    path('account/', views.AccountListView.as_view(), name="account-list"),
    path('account/<int:pk>/', views.AccountDetailView.as_view(), name="account-detail"), # todo: change 'pk' to 'username'
]

traveler/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.core.validators import MinLengthValidator
from django.urls import reverse, reverse_lazy
from ckeditor.fields import RichTextField
from .utils import file_size_validator, defaul_raitings
from django.core.validators import MinLengthValidator


User = get_user_model()


class Tag(models.Model):
    name = models.CharField(verbose_name="Тег", max_length=50, unique=True)

    def save(self, *args, **kwargs):
        self.name = self.name.replace(" ", "").lower()
        super(Tag, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


class Country(models.Model):
    name = models.CharField(verbose_name="Страна", max_length=120, unique=True)
    description = RichTextField(verbose_name="Описание страны", null=True, blank=True)

    def __str__(self):
        return self.name


class Account(models.Model): # todo: попробовать сделать через кастомный класс AbstractUser ...
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    tag_subs = models.ManyToManyField(Tag, blank=True, default=None, related_name='tag_mtm')
    country_subs = models.ManyToManyField(Country, blank=True, default=None, related_name='country_mtm')
    user_subs = models.ManyToManyField("self", blank=True, default=None, related_name="subscribers")

    def __str__(self):
        return f"<Account: {self.user.username}>"


class Post(models.Model):
    author = models.ForeignKey(Account, on_delete=models.CASCADE, verbose_name="Пользователь")
    title = models.CharField(verbose_name="Заголовок", max_length=150)
    country = models.ForeignKey(Country, on_delete=models.CASCADE, verbose_name="Страна", null=True)
    content = models.TextField(verbose_name="Содержимое публикации", validators=[MinLengthValidator(3)])
    timestamp = models.DateTimeField(verbose_name="Время", auto_now_add=True)
    tags = models.ManyToManyField(Tag, blank=True, default=None, related_name="post_tag_rel")
    raiting = models.JSONField(verbose_name="Рейтинг", default=defaul_raitings, null=True, blank=True)
    visible = models.BooleanField(verbose_name="Показывать публикацию", default=True)

    def get_absolute_url(self):
        return reverse_lazy("traveler:post-detail", kwargs={"pk": self.id})

    def __str__(self):
        return self.title


class PostImage(models.Model):
    post = models.ForeignKey(Post, verbose_name="Публикация", on_delete=models.CASCADE)
    picture = models.ImageField(verbose_name="Изображение", upload_to="pictures", validators=[file_size_validator],)
    is_main_pic = models.BooleanField(verbose_name="Основное фото", default=False)

    def __str__(self):
        return "Изображение к " + self.post.title


class PostComment(models.Model):
    post = models.ForeignKey(Post, verbose_name="Публикация", on_delete=models.CASCADE)
    author = models.ForeignKey(Account, verbose_name="Автор (клиент)", on_delete=models.CASCADE)
    comment = RichTextField("Комментарий", null=True, blank=True)
    timestamp = models.DateTimeField(verbose_name="Время", auto_now_add=True)

    def __str__(self):
        return "Комментарий на " + self.post.title




traveler/forms.py
from django.forms import forms, ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from .models import *


User = get_user_model()


class PostCreateForm(ModelForm):
    class Meta:
        model = Post
        fields = '__all__'
        exclude = ["raiting", "timestamp", "tags"]


class UserSignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["first_name", 'username', 'email', 'password1', 'password2']

traveler/api/views.py
from rest_framework.generics import (ListCreateAPIView, RetrieveUpdateDestroyAPIView,
                                     ListAPIView, CreateAPIView)
from rest_framework.permissions import AllowAny, IsAdminUser
from traveler.models import (Tag, Country, Account,
                             Post, PostImage, PostComment)
from .serializers import (TagSerializer, CountrySerializer,
                          AccountSerializer, PostSerializer, PostListCreateSerializer,
                          PostImageSerializer, PostCommentSerializer,
                          UserSignupSerializer)

from django.contrib.auth import get_user_model


User = get_user_model()


class CountryListAPIView(ListCreateAPIView):
    serializer_class = CountrySerializer
    queryset = Country.objects.all()


class CountryRUDAPIView(RetrieveUpdateDestroyAPIView):
    serializer_class = CountrySerializer
    queryset = Country.objects.all()


class UserSignupAPIView(CreateAPIView):
    serializer_class = UserSignupSerializer
    queryset = User.objects.all()
    permission_classes = [IsAdminUser]


class AccountListAPIView(ListAPIView):
    serializer_class = AccountSerializer
    queryset = Account.objects.all()

class AccountRUDAPIView(RetrieveUpdateDestroyAPIView):
    serializer_class = AccountSerializer
    queryset = Account.objects.all()


class PostListAPIView(ListCreateAPIView):
    serializer_class = PostListCreateSerializer
    queryset = Post.objects.all()


class PostRUDAPIView(RetrieveUpdateDestroyAPIView):
    serializer_class = PostSerializer
    queryset = Post.objects.all()


class PostImageListAPIView(ListCreateAPIView):
    serializer_class = PostImageSerializer
    queryset = PostComment.objects.all()


class PostImageRUDAPIView(RetrieveUpdateDestroyAPIView):
    serializer_class = PostImageSerializer
    queryset = PostComment.objects.all()

class PostCommentListAPIView(ListCreateAPIView):
    serializer_class = PostCommentSerializer
    queryset = PostComment.objects.all()


class PostCommentRUDAPIView(RetrieveUpdateDestroyAPIView):
    serializer_class = PostCommentSerializer
    queryset = PostComment.objects.all()




traveler/templates/account_details.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container">
        <div class="col-6">
            <h5 class="my-4">Данные пользователя:</h5>
            <div class="group">

                    <fieldset disabled class="list-group-item">
                        <div class="mb-3">
                            <label for="usernameDash" class="form-label">Логин</label>
                            <div class="input-group">
                                <span class="input-group-text" id="basic-addon1">@</span>
                                <input type="text" class="form-control disabled" placeholder="{{ account.user.username }}"
                                       id="usernameDash" aria-label="Username" aria-describedby="basic-addon1"/>
                            </div>
                        </div>
                        <div class="mb-3">
                            <label for="nameDash" class="form-label">Имя</label>
                            <input type="text" id="nameDash" name="nameDash"
                                   class="form-control" placeholder="{{ account.user.first_name }}"/>
                        </div>
                        <div class="mb-3">
                            <label for="lastNameDash" class="form-label">Фамилия</label>
                            <input type="text" id="lastNameDash" name="nameDash"
                                   class="form-control" placeholder="{{ account.user.last_name }}"/>
                        </div>
                    </fieldset>
            </div>

            <h5 class="my-4">Публикации:</h5>
            <div class="group">
                <div class="list-group-item p-0 mb-5">
                    <div class="toSlick user-dash-carousel">
                        {% for post in account_posts %}
                            {% include 'card_post.html' with post=post %}
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

traveler/templates/account_list.html
{% extends 'base.html' %}

{% block content %}
    <div class="container py-4">

        <h3 class="h3">Список Пользователей</h3>
        {% for key, val in account_list.items %}
            <div><h5>{{ key }} -- {{ val }}</h5></div>
        {% endfor %}

        <ul class="list-group col-8">
            {% for account, post_list in account_data.items %}
                <li class="list-group-item list-group-item-action px-3 d-flex justify-content-between align-items-center">
                    <a href="{% url 'traveler:account-detail' account.id %}"
                       class="list-group-item list-group-item-action">
                        <span class="list-group-item">{{ account.user.first_name }}</span>
                        <span class="list-group-item">{{ account.post_set.count }} posts</span>
                        <span class="list-group-item">{{ post_list.count}} countries</span>
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

traveler/templates/card_post.html
{% if post.visible %}
<div class="card mb-4 pb-3">
    <div class="card-img-top img-carosel">
        <img src="{{ post.postimage_set.first.picture.url }}" class="" alt="">
    </div>

    <div class="card-body">
        <div class="card-title">
            <h4>{{ post.title }}</h4>
            <small class="text-muted">
                by {{ post.author.user.first_name }} {{ post.author.user.last_name }}  |
            </small>
            <span class="text-muted">{{ post.timestamp|timesince }}</span>  |
            <span class="text-muted"><i class="bi bi-chat-dots"></i>  {{ post.postcomment_set.count }}</span>
            <p class="text-muted"><b>{{ post.country.name }}</b></p>
        </div>

        <div class="card-content">
            {{ post.content|slice:":150"|safe }}...
        </div>

        <div class="text-muted py-3">
            {% for tag in post.tags.all %}
                <span><i class="bi bi-tag"></i> {{ tag }} </span>
            {% endfor %}
        </div>
        <a href="{% url 'traveler:post-detail' post.id %}" class="btn btn-outline-primary col-3">Подробно</a>
    </div>
</div>
{% endif %}

traveler/templates/header.html
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top px-5">
        <div class="container-fluid">
            <a class="navbar-brand fw-bold" href="{% url 'traveler:home' %}">Traveler</a>
            <button class="navbar-toggler" type="button" id="togglerBtn">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                {% if request.user.is_authenticated %}
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{% url 'traveler:country-list' %}">Список стран</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'traveler:account-list' %}">Пользователи</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'traveler:dash' %}">Кабинет</a>
                        </li>
                    </ul>

                    <span class="text-light mx-3 float-end">{{ request.user }}</span>
                    <a href="{% url 'traveler:logout' %}" class="btn btn-outline-light" type="submit">Выйти</a>

                {% else %}
                    <a href="{% url 'traveler:login' %}" class="btn btn-outline-light bd-highlight" type="submit">Войти</a>
                {% endif %}
            </div>
        </div>
    </nav>
</header>

traveler/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/slick.css' %}"/>
{% endblock %}

{% block content %}

    {% if request.user.is_authenticated %}
        {% include 'side_menu.html' %}

        <div class="container col-7 pb-3">
            <!-- MAIN subscription feed -->
            <div class="posts-block subs-all">
                <h4 class="py-4">Все публикации по вашим подпискам</h4>

                {% for post in page_obj %}
                    {% include 'card_post.html' %}
                {% endfor %}

                <div class="pagination">
                    <span class="step-links">
                        {% if page_obj.has_previous %}
                            <a href="?page=1">&laquo; first</a>
                            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                        {% endif %}

                        <span class="current">
                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                        </span>

                        {% if page_obj.has_next %}
                            <a href="?page={{ page_obj.next_page_number }}">next</a>
                            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                        {% endif %}
                    </span>
                </div>
            </div>

            <!-- User subscription posts -->
            <div class="posts-block subs-account visually-hidden">
                <h4 class="py-4">Публикации по подпискам на Пользователей</h4>
                {% for post in user_subs_posts %}
                    {% include 'card_post.html' %}
                {% endfor %}
            </div>

            <!-- Tag subscription posts -->
            <div class="posts-block subs-tag visually-hidden">
                <h4 class="py-4">Публикации по подпискам на Теги</h4>
                {% for post in tag_subs_posts %}
                    {% include 'card_post.html' %}
                {% endfor %}
            </div>

            <!-- Country subscription posts -->
            <div class="posts-block subs-country visually-hidden">
                <h4 class="py-4">Публикации по подпискам на Страны</h4>
                {% for post in country_subs_posts %}
                    {% include 'card_post.html' %}
                {% endfor %}
            </div>
        </div>

    {% else %}
        <div class="container col-7">
            <h4 class="py-4">Последние 10 публикаций</h4>
            {% for post in posts %}
                {% include 'card_post.html' %}
            {% endfor %}

            <div class="row py-5">
                <a href="{% url 'traveler:login' %}" class="btn btn-primary col">Читать далее</a>
            </div>
        </div>
    {% endif %}

{% endblock %}


{% block js %}
    <script type="text/javascript" src="{% static 'js/slick.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/index.js' %}"></script>
{% endblock %}

traveler/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Login{% endblock %}

{% block css %}
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/login_signup.css' %}">
{% endblock %}

{% block side_recents %}
    {% include 'side_recents.html' with class="hidden"%}
{% endblock %}

{% block content %}
<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
                    <form method="POST" action="">
                        {% csrf_token %}
                        <div class="input-group mb-3">
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="fas fa-user"></i></span>
                            </div>
                            <input type="text" name="username" placeholder="Username..." class="form-control">
                        </div>
                        <div class="input-group mb-2">
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="fas fa-key"></i></span>
                            </div>
                            <input type="password" name="password" placeholder="Password..." class="form-control">
                        </div>
                        <div class="d-flex justify-content-center mt-3 login_container">
                            <input class="btn login_btn" type="submit" value="Login">
                        </div>
                    </form>
				</div>

                {% if messages %}
                    {% for message in messages %}
                        <br><p class="btn btn-default btn-lg disabled">{{ message }}</p>
                    {% endfor %}
                {% endif %}

				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'traveler:signup' %}" class="ml-2">Sign Up</a>
					</div>

				</div>
			</div>
		</div>
	</div>
{% endblock %}

traveler/templates/post_details.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/slick.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/slick-theme.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/bootstrap-icons.css' %}">
{% endblock %}

{% block content %}
    <div class="container py-5 col-7">
    {% if post.visible %}

        <h3 class="mb-4">{{ post.title}}</h3>
        <p class="mb-4">
            Автор: <strong class="text-muted">{{ post.author.user.first_name }} {{ post.author.user.last_name }}</strong><br>
            Дата: <strong class="text-muted">{{ post.timestamp | date }}</strong>
            <p class="py-0 my-1"><b>{{ post.country.name }}</b></p>
        </p>

        <div class="card-img-top img-carosel toSlick mb-4">
            {% for image in post.postimage_set.all %}
                <img src="{{ image.picture.url }}" class="slick-item slick-image" alt="">
            {% endfor %}
        </div>

        <p class="text-justify">{{ post.content|safe }}</p>

        <div class="text-muted py-3">
            {% for tag in post.tags.all %}
                <span><i class="bi bi-tag"></i> {{ tag }} </span>
            {% endfor %}
        </div>

        <div class="row m-auto">
            <button data-key_id="{{ post.id }}" class="like btn btn-outline-success col-2 me-md-2 btn-sm">
                <span>{{ post.raiting.sum }}</span>&nbsp;
                Like</button>
            <button data-key_id="{{ post.id }}" class="dislike btn btn-outline-secondary col-2 me-md-2 btn-sm">
                <span>{{ post.raiting.dis }}</span>&nbsp;
                Dislike</button>
            {% if post.author == request.user.account %}
                <form action="" method="post" class="col-2 ms-md-auto">{% csrf_token %}
                    <button id="removePost" class="col-12 btn btn-outline-danger btn-sm" type="submit">Delete</button>
                </form>
            {% endif %}
        </div>

        <!-- Comments -->
        <div class="comments my-5">
            <h5 class="mb-4">Комментарии:</h5>
            {% for comment in post.postcomment_set.all %}
                <div class="comment border-1 mb-4" id="comment_key_{{ comment.id }}">
                    <p class="text-muted">@{{ comment.author.user.username }}  |  {{ comment.timestamp }}</p>
                    <div class="ps-5">{{ comment.comment | safe }}</div>

                    {% if comment.author == request.user.account %}
                        <form class="removeComment" action="#">{% csrf_token %}
                            <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                                <input type="hidden" name="post_comment_info" value="{{ comment.id }}">
                                <button class="btn btn-outline-danger me-md-2 btn-sm">
                                    <i class="bi bi-trash"></i>
                                    Remove
                                </button>
                            </div>
                        </form>
                    {% endif %}
                </div>

            {% endfor %}

        </div>
        <!-- Add comment -->
        <form id="addComment" action="" method="post">
            {% csrf_token %}
            <div class="form-floating mb-3">
                <textarea class="form-control" placeholder="Leave a comment here" id="floatingTextarea2"
                          style="height: 100px" name="post_comment"></textarea>
                <label for="floatingTextarea2">Ваш комментарий . . .</label>
            </div>
            <button class="btn btn-primary float-end">Comment</button>
        </form>

    {% else %}
        <div class="col-6 ms-auto">
            <h5 class="h5">ДАННЫЙ ПОСТ ЗАБЛОКИРОВАН</h5>
        </div>
    {% endif %}
    </div>

{% endblock %}

{% block js %}
    <script type="text/javascript" src="{% static 'js/slick.min.js' %}"></script>
    <script>
    $(document).ready(function () {
        $('.toSlick').slick({
            arrows: true,
            mobileFirst: false,
        });

        {#const accountId = JSON.parse("{{ request.user.account.id|escapejs }}");#}
        {#const username = JSON.parse("{{ request.user.username|escapejs }}");#}
        {#const postId = JSON.parse("{{ post.id|escapejs }}");#}

        const accountId = {% autoescape off %}"{{ request.user.account.id }}"{% endautoescape %}
        const username = {% autoescape off %}"{{ request.user.username }}"{% endautoescape %}
        const postId = {% autoescape off %}"{{ post.id }}"{% endautoescape %}


        $("#addComment").submit((e) => {
            e.preventDefault();
            let form = e.target;
            let csrftoken = $(form.elements.csrfmiddlewaretoken).val();
            fetch(`/api/comment/`, {
                mode: 'same-origin',
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json;charset=utf-8',
                    "X-CSRFToken": csrftoken,
                },
                body: JSON.stringify({
                    comment: $(form.elements.post_comment).val(),
                    author: accountId,
                    post: postId,
                })
            })
                .then(status => {
                    if (status.ok) {
                        return status.json()
                    }
                })
                .then(data => {
                    $(".comments").append(`
                        <div class="comment border-1 mb-4" id="comment_key_${data.id}">
                            <p class="text-muted">@${username}  |  ${new Date(data.timestamp).toLocaleDateString()}</p>
                            <div class="ps-5">${data.comment}</div>
                        </div>
                    `);

                    if (Number(data.author) === Number(accountId)) {
                        $(`.comments > #comment_key_${data.id}`).append(`
                            <form class="removeComment" action="#">{% csrf_token %}
                                <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                                    <input type="hidden" name="post_comment_info" value="${data.id}">
                                    <button class="btn btn-outline-danger me-md-2 btn-sm" type="submit">
                                        <i class="bi bi-trash"></i>
                                        Remove
                                    </button>
                                </div>
                            </form>
                        `);
                    };

                    $("#floatingTextarea2").val('');
                });
        });

        $("body").on('submit', "form.removeComment", (e)=>{
            e.preventDefault();
            let form = e.target;
            let commentId = $(form.elements.post_comment_info).val();
            let csrftoken = $(form.elements.csrfmiddlewaretoken).val();

            fetch(`/api/comment/${commentId}/`, {
                mode: 'same-origin',
                method: 'DELETE',
                headers: {
                    'Content-Type': 'application/json;charset=utf-8',
                    "X-CSRFToken": csrftoken,
                }
            })
                .then(status => {
                    if(status.ok){$(`#comment_key_${commentId}`).remove()}
                });
        });

        const raitingAction = (btnSelector, propInc, propDec)=>{
            btnSelector.click((e) => {
                e.preventDefault();
                let btn = e.target;
                let post_id = $(btn).data("key_id");
                post_rud(postId).then((data) => {
                    let userLike = +data.raiting[username] && propInc === "sum" ? 1 : 0; // to make disabled button in future
                    post_rud(postId, "PATCH",
                        {raiting: {[propDec]: data.raiting[propDec], [propInc]: data.raiting[propInc] + 1, [username]: userLike}})
                        .then((res) => {
                            btnSelector.children("span").html(res.raiting[propInc])
                        });
                });
            });
        }

        raitingAction($(".dislike"), "dis", "sum");
        raitingAction($(".like"), "sum", "dis");

        const post_rud = async (postId, method = 'GET', data = {}) => {
            let csrftoken = Cookies.get("csrftoken");

            const response = await fetch(`/api/post/${postId}/`, {
                method: method,
                headers: {
                    'Content-Type': 'application/json;charset=utf-8',
                    "X-CSRFToken": csrftoken,
                },
                body: method === 'GET' ? null : JSON.stringify(data),
            });

            return await response.json();
        };

    });
    // todo: refactor all with react.js
    </script>

{% endblock %}

traveler/templates/side_menu.html
<div id="mySidenav" class="sidenav">
    <a href="javascript:void(0)" class="closebtn">&times;</a>
    <a class="menu-link" data-filter="subs-all" href="#">Общий</a>
    <a class="menu-link" data-filter="subs-tag" href="#">По тегам</a>
    <a class="menu-link" data-filter="subs-country" href="#">По странам</a>
    <a class="menu-link" data-filter="subs-account" href="#">По пользователям</a>
{#    <a class="btn btn-outline-dark btn-dash" href="{% url 'traveler:country-list' %}">Список стран</a>#}
{#    <a class="btn btn-outline-dark btn-dash" href="{% url 'traveler:dash' %}">Кабинет</a>#}
</div>

<span class="menu-btn position-fixed align-self-stretch col-0 bg-dark text-light px-2">&#9776;</span>




traveler/templates/side_recents.html
<div class="col col-2 sidebar-recent-wrapper float-end list-group-item {{ class }}">

    <div class="sidebar-recent py-2">
        <!--================ RECENT POSTS =================-->
        <aside class="mb-4">
            <h5>Последние 3 публикации</h5>
            {% for post in post_recent %}
                <div class="px-3">

                    <div class="row border">
                        <div class="image col-3">
                            <img src="{{ post.postimage_set.first.picture.url }}" alt="" class="">
                        </div>

                        <a href="{% url 'traveler:post-detail' post.id %}" class="col-7 post-title">{{ post.title }}</a>
                    </div>
                </div>
            {% endfor %}
        </aside>

        <!--================ TAG CLOUD =================-->
            <h5>Теги</h5>
        <aside class="overflow-auto my-4 tags-cloud">
            {% for tag in tag_list %}
                <a href="#" class="btn btn-outline-secondary btn-sm">{{ tag }}</a>
            {% endfor %}
        </aside>

        <!--================ TOP 5 USERS =================-->
        <aside class="my-4">
            <h5>Топ пользователей</h5>
            {% for account in account_top %}
                <a href="{% url 'traveler:account-detail' account.id %}" class="btn btn-outline-dark">{{ account.user }}</a>
            {% endfor %}
        </aside>

    </div>
</div>